### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by irawancepu** [Chupaka/Delphi-RouterOS-API#1]
I already compile APITest on D2007. Everything works well. 
However almost no documentation available.
Till now i don't know which commands are supported and which commands are not supported.
Cause of this, message : trap: no such command or directory became my friend.
One of command i need to work actually are system/reboot and ping.
Please give me some help.

best regard
irawan

ps: i manage many mikrotik wireless radios. when one them is down, i need to reboot its partner.

**Comment by Chupaka** [comment]
From the [official manual](https://wiki.mikrotik.com/wiki/Manual:API): "Name of command word should begin with '/'. Names of commands closely follow CLI, with spaces replaced with '/'"

So what you're looking for is "/system/reboot" and "/ping".

**Comment by irawancepu** [comment]
Usually i use Winbox.exe to handle my daily work.
Many features available in Winbox.
Using RouterOSAPI to handle my daily job is different story.
Everything must be written fully.
Learn many new things here.
To reboot, '/system/reboot' and the router then reboot.
Ping job
  /ping
  =address=192.168.100.1
and the replies shown in memo.
Find wireless interface :
'/interface/wireless/print'
and i got wireless interface shown in memo.

In winbox, new terminal, 'interface monitor interface=wlan1'
and the trafic shown in terminal how to do this in RouterOSAPI?

best regard
irawan

ps;
i want to use RouterOSAPI to help me in my daily job.
winbox is help me much actually, except for statistic.
the problem arise when i have to leave my router and i want to monitor my
router.
i want to monitor traffic on my selected interface on web browser.
here i'm stuck for years, i'm still using RouterOSAPI ver 1.1.
for web server i will using Indy.
actually i don't want to disturb you.
however the one who know RouterOSAPI an RouterOS is you.
then i open issue on GitHub.



On Thu, Jul 19, 2018 at 3:35 PM, Pavel Skuratovich <notifications@github.com

**Comment by Chupaka** [comment]
> In winbox, new terminal, 'interface monitor interface=wlan1'
> and the trafic shown in terminal how to do this in RouterOSAPI?

"interface monitor" is the beginnig of the command "/interface monitor-traffic" (use \<Tab\> to complete your commands in Terminal). Shortening is not allowed in API, you must write full command name:

```
/interface/monitor-traffic
=interface=ether1
```
